# ---------- Stage 1: Builder ----------
FROM python:3.10-slim AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

COPY . .


# ---------- Stage 2: Distroless ----------
FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=builder /install /usr/local
COPY --from=builder /app /app

ENV PORT=5000
ENV ENV=production

EXPOSE 5000

CMD ["app.py"]
